#ifndef ERROR_H

# define ERROR_H
# define MALLOC_ERR			"MEMORY ALLOCATION ERROR"
# define OPEN_FILE_ERR		"OPEN FILE ERROR"
# define CREATE_FILE_ERR	"FILE CREATION ERROR"
# define READ_FILE_ERR		"READ FILE ERROR"

#endif